### ISSUE TITLE
Shädows handles big lights poorly

### ISSUE THREAD

**Issue by ghost** [matiasah/shadows#29]
Huge lights in shädows performs poorly (1000+ range), however scaling up the lights runs fine but is not very clean.

**Comment by matiasah** [comment]
Have you tried using a star for the same purpose? Or, do you need the light not to be covered by shadows casted from rooms?

**Comment by ghost** [comment]
The issue is purely with moving very large lights that needs to be able to affect other lights, opened this issue for a friend who experienced some very odd lag when he used a large light that follows around the player. Even removing everything from the game except Shädows resulted in weird lag when moving a 1000+ light around.

**Comment by matiasah** [comment]
Normal lights will have a canvas with a size of two ( 2 * radius ) x ( 2 * radius ), thus using a 1000 pixels radius is going to work very badly especially when using shaders.

Stars, however, will only have a Canvas size that is equal to the graphics size and will only render what is actually visible on the screen, it's made to handle bigger light sizes and it should be used whenever you need them to be dynamic.

You could perhaps tell your friend to test the stars instead of the lights for that scenario.

**Comment by ghost** [comment]
Oh okay thank you

**Comment by Skeletonxf** [comment]
Can this information also be provided on the [wiki](https://github.com/matiasah/shadows/wiki/Light)? I don't think it is very clear what the difference between stars and lights are.

**Comment by matiasah** [comment]
I have modified the Light's wiki, I'm probably going to add more information as I remember it. I could've developed a architectural blueprint for this project but I didn't have the knowledge back then. As it currently is, is it good enough now?

**Comment by Skeletonxf** [comment]
Generally quite good though I am a little confused by this

> The size of the star's canvases are the size of the graphics

What is "the graphics" here? The size of my LightWorld or perhaps the size of my window?

**Comment by matiasah** [comment]
Is it better if we call it, the love2d window graphics?
