### ISSUE TITLE
Light not showing up on Android

### ISSUE THREAD

**Issue by Fabiooo98** [matiasah/shadows#33]
Hello, 

We are currently using your light engine to create a little mobile game. However, if we run our game on an Android device the light does not show up and everything is black, except the text that is printed after the LightWorld is drawn. If I run the game on PC however, the light and shadows all work as intended.

I read in other issues that the engine would run on mobile aswell. So, I was wondering if you might have an idea what the issue could be?

Thanks in advance:)

**Comment by matiasah** [comment]
You could check #30 if you're running on Mac.

**Comment by Skeletonxf** [comment]
Android uses slightly different shaders and things which work on desktop Love2d may not work on mobile due to this.

I opened pull requests previously when I encountered compatibility issues on this. You might be able to apply similar tweaks to fix any new compatibility issues that have been introduced.

https://github.com/matiasah/shadows/pull/3
https://github.com/matiasah/shadows/pull/1

**Comment by matiasah** [comment]
The only solution I can think of is making this library again from scratch.

**Comment by Fabiooo98** [comment]
Alright, thank you for your help!
