### ISSUE TITLE
Test on OpenGL ES

### ISSUE THREAD

**Issue by matiasah** [matiasah/shadows#5]
I didn't test the modifications on the shader code for OpenGL ES yet, if anyone wants to try it you can use the DEMO.love file.

**Comment by Skeletonxf** [comment]
I get the following error (note there may be typos as I typed this from my phone, rather than finding a way to copy the message)
Cannot compile pixel shader code
0:15: S0001: No matching overload for function 'pow' found
0:15: Warning: Expected prototype is 'pow (float, float)' orpow 'pow (vec2, vec2)' orpow 'pow (vec3, vec3)' orpow 'pow (vec4, vec4)'

Traceback
[C]: in function 'newShader'
shadows/Shaders.lua:156 in main chunk
shadows/init.lua:28 in main chunck
.....

**Comment by matiasah** [comment]
Can you tell me if it works with a626528 ?

**Comment by Skeletonxf** [comment]
No crashes, game loads and 'runs' though admittedly at a very low framerate :)

**Comment by matiasah** [comment]
Unfortunately the only possible way I could fix the framerate issue is by not relying on canvases, also the demo uses Tiled and it constantly updates a canvas every frame (no sense, lol).

**Comment by Skeletonxf** [comment]
As long as the engine itself hasn't had a big drop in performance then there's no problem. The game I've been working on gets good enough framerate considering how old my phone is. :)
