### ISSUE TITLE
Sprite shadowcasting

### ISSUE THREAD

**Issue by Sungray** [matiasah/shadows#9]
Would love the possibility to cast a shadow with the same shape as a sprite or quad. For instance, take a 32x32 quad. The "shadow image" would be basically the same as the quad, except only black.

**Comment by matiasah** [comment]
What do you mean exactly? You can't force a sprite to have 6 vertices when you cast it's shadow as if it was a quad.

**Comment by Skeletonxf** [comment]
I think the issue is related to this post: https://love2d.org/forums/viewtopic.php?f=5&t=82525&sid=6eca11d4deeca66d7dc891e1252de400&start=10

Basically being able to convert love2d ImageData to a Shape for use in shading.

**Comment by matiasah** [comment]
I could make it cast a shadow & give it a normal map flag for custom textures, but the shape wouldn't get any extortion effect unlike the polygon shape.

**Comment by matiasah** [comment]
I think the best way to describe this issue is the following:
You can't cast the shadow of a sprite because it's not 3D, if you learn something about dimensions you will understand that when you want to cast the shadow of a shape, it's shadow will be one dimension less than the original shape

If you're in 4D spatial, it goes 3D. If you're 3D, it goes 2D. If you're 2D, it goes 1D.

Your shape in real life has 3D dimensions (X,Y,Z) where Z is for height and X,Y for width. If you try to cast a shadow of a 2D shape it only makes a 1D shadow, doesn't make much sense at all.

Why does the engine itself work? Because it contains a additional field for body height (z), so there is no limitation within that.

**Comment by matiasah** [comment]
We could possibly implement height maps, that would give us the possibility to implement a 3rd dimension.

**Comment by matiasah** [comment]
Does this suit your needs?
https://github.com/matiasah/shadows/wiki/ImageShadow
